import { normalizePartyId } from './party-aliases';

/** Full legal / common names for party codes used in ECI / News18 feeds */
const PARTY_FULL_NAMES: Record<string, string> = {
  BJP: 'Bharatiya Janata Party',
  INC: 'Indian National Congress',
  DMK: 'Dravida Munnetra Kazhagam',
  AIADMK: 'All India Anna Dravida Munnetra Kazhagam',
  TMC: 'All India Trinamool Congress',
  AITC: 'All India Trinamool Congress',
  CPI: 'Communist Party of India',
  CPM: 'Communist Party of India (Marxist)',
  CPIM: 'Communist Party of India (Marxist)',
  SP: 'Samajwadi Party',
  AGP: 'Asom Gana Parishad',
  UPPL: 'United People’s Party Liberal',
  AIUDF: 'All India United Democratic Front',
  NTK: 'Nam Tamilar Katchi',
  TVK: 'Tamilaga Vettri Kazhagam',
  PMK: 'Pattali Makkal Katchi',
  VCK: 'Viduthalai Chiruthaigal Katchi',
  IUML: 'Indian Union Muslim League',
  BDJS: 'Bharath Dharma Jana Sena',
  AINRC: 'All India N.R. Congress',
  RSP: 'Revolutionary Socialist Party',
  AIFB: 'All India Forward Bloc',
  AIMIM: 'All India Majlis-e-Ittehadul Muslimeen',
  IND: 'Independent',
  OTH: 'Other parties / Independents',
  OTHERS: 'Other parties / Independents',
  MDMK: 'Marumalarchi Dravida Munnetra Kazhagam',
  DMDK: 'Desiya Murpokku Dravida Kazhagam',
  NCP: 'Nationalist Congress Party',
  KCM: 'Kerala Congress (M)',
  'KC(M)': 'Kerala Congress (M)',
  KC: 'Kerala Congress',
  JDS: 'Janata Dal (Secular)',
  RSMP: 'Rally for Socialist Movement Party',
  BGPM: 'Bharatiya Gorkha Prajatantra Morcha',
  BSP: 'Bahujan Samaj Party',
  AAP: 'Aam Aadmi Party',
  JD: 'Janata Dal',
  JD_U: 'Janata Dal (United)',
  JDU: 'Janata Dal (United)',
  BPF: 'Bodoland People’s Front',
  AJP: 'Assam Jatiya Parishad',
  GGP: 'Gana Suraksha Party',
  MCOI: 'Minority Congress of India',
  INL: 'Indian National League',
  NSC: 'National Secular Conference',
  CS: 'Congress (Secular)',
  LTJD: 'Loktantrik Janata Dal',
  RMPI: 'Revolutionary Marxist Party of India',
  KCJ: 'Kerala Congress (Jacob)',
  KCB: 'Kerala Congress (B)',
  JKC: 'Janata Kerala Congress',
  MAMAK: 'Manithaneya Makkal Katchi',
  PT: 'Puthiya Tamilagam',
  PPID: 'Regional party',
  SDPI: 'Social Democratic Party of India',
  GSP: 'Gondwana Ganatantra Party',
  WBSP: 'West Bengal Socialist Party',
  SPI: 'Socialist Party of India',
  BNARP: 'Bharatiya Navashakti Party',
  IUC: 'Indian Union Congress',
  RAJSP: 'Rashtriya Janata Samaj Party',
  BUP: 'Bharatiya Tribal Party',
  WPI: 'Welfare Party of India',
  AISF: 'All India Students Federation',
  VINP: 'Vikas Insaf Party',
  JADP: 'Jan Adhikar Party',
  PFDS: 'People’s Party of Democratic Socialism',
  HSP: 'Hindustani Samaj Party',
  BMP: 'Bahujan Mukti Party',
  JSGP: 'Jan Sangharsh Party',
  INF: 'Indian National Forum',
  BNJD: 'Bharatiya Nyay Dal',
  JUP: 'Janata United Party',
  JLKM: 'Jan Lokhit Morcha',
  MBMP: 'Mahan Bahujan Morcha Party',
  NCVP: 'National Vikas Party',
  API: 'Adivasi Party of India',
  AB: 'Ambedkarite Party',
  KMPPU: 'Kannada Paksha',
  AJUN: 'Aaj Untied Navnirman',
  MPI: 'Mahan Dal',
  GSD: 'Gondwana Samaj Dal',
  NBNPP: 'Nav Bharat Nirman Party',
  ABGL: 'Amra Bangali',
};

export function partyFullName(partyId: string): string {
  const id = normalizePartyId(partyId);
  return PARTY_FULL_NAMES[id] ?? (partyId.trim() || 'Unknown');
}

/** One-line label: Full name with abbreviation when known */
export function partyLabelLine(partyId: string): string {
  const id = normalizePartyId(partyId);
  const full = PARTY_FULL_NAMES[id];
  if (!full) return id || partyId;
  if (full === id || id === 'OTH') return full;
  return `${full} (${id})`;
}
